// <auto-generated />
using System;
using KutuphaneOtomasyonu.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneOtomasyonu.API.Migrations
{
    [DbContext(typeof(KutuphaneDbContext))]
    [Migration("20250718131544_AddSayfaSayisiToKitap")]
    partial class AddSayfaSayisiToKitap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("kategori_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kategori_adi");

                    b.HasKey("KategoriId");

                    b.HasIndex("KategoriAdi")
                        .IsUnique();

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kitap", b =>
                {
                    b.Property<string>("KitapId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kitap_id");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aciklama");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("kategori_id");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("kitap_adi");

                    b.Property<int>("MevcutAdet")
                        .HasColumnType("int")
                        .HasColumnName("mevcut_adet");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("int")
                        .HasColumnName("sayfa_sayisi");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("int")
                        .HasColumnName("stok_adedi");

                    b.Property<int>("YayinYili")
                        .HasColumnType("int")
                        .HasColumnName("yayin_yili");

                    b.Property<int>("YazarId")
                        .HasColumnType("int")
                        .HasColumnName("yazar_id");

                    b.HasKey("KitapId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("YazarId");

                    b.ToTable("Kitaplar", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("kullanici_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("kayit_tarihi");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rol");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sifre_hash");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("soyad");

                    b.HasKey("KullaniciId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.OduncKayit", b =>
                {
                    b.Property<int>("OduncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("odunc_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OduncId"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("durum");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("iade_tarihi");

                    b.Property<string>("KitapId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kitap_id");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OduncAlmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("odunc_alma_tarihi");

                    b.Property<DateTime>("SonTeslimTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("son_teslim_tarihi");

                    b.HasKey("OduncId");

                    b.HasIndex("KitapId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("OduncKayitlari", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Yazar", b =>
                {
                    b.Property<int>("YazarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("yazar_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("Biyografi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("biyografi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("soyad");

                    b.HasKey("YazarId");

                    b.ToTable("Yazarlar", (string)null);
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kitap", b =>
                {
                    b.HasOne("KutuphaneOtomasyonu.API.Entities.Kategori", "Kategori")
                        .WithMany("Kitaplari")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KutuphaneOtomasyonu.API.Entities.Yazar", "Yazar")
                        .WithMany("Kitaplari")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.OduncKayit", b =>
                {
                    b.HasOne("KutuphaneOtomasyonu.API.Entities.Kitap", "Kitap")
                        .WithMany("OduncKayitlari")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KutuphaneOtomasyonu.API.Entities.Kullanici", "Kullanici")
                        .WithMany("OduncKayitlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kategori", b =>
                {
                    b.Navigation("Kitaplari");
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kitap", b =>
                {
                    b.Navigation("OduncKayitlari");
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Kullanici", b =>
                {
                    b.Navigation("OduncKayitlari");
                });

            modelBuilder.Entity("KutuphaneOtomasyonu.API.Entities.Yazar", b =>
                {
                    b.Navigation("Kitaplari");
                });
#pragma warning restore 612, 618
        }
    }
}
